//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.14 at 11:43:42 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://services.ttj.com/hello-service", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ttj.services.hello_service;
